# Generated by Django 6.0.1 on 2026-02-09 10:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Model name (e.g., health_v1)', max_length=100, unique=True)),
                ('version', models.CharField(help_text='Model version', max_length=20)),
                ('model_type', models.CharField(choices=[('health', 'Health Prediction'), ('behavior', 'Behavior Analysis'), ('estrus', 'Estrus Detection'), ('anomaly', 'Anomaly Detection')], max_length=50)),
                ('model_file', models.CharField(help_text='Path to saved model file', max_length=200)),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy score (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Currently in use')),
                ('description', models.TextField(blank=True, help_text='Model description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('health', 'Health Prediction'), ('behavior', 'Behavior Prediction'), ('estrus', 'Estrus Detection'), ('anomaly', 'Anomaly Detection')], max_length=50)),
                ('model_name', models.CharField(help_text='Model used', max_length=100)),
                ('model_version', models.CharField(help_text='Model version', max_length=20)),
                ('predicted_value', models.CharField(help_text="Prediction result (e.g., 'SICK', 'GRAZING')", max_length=100)),
                ('confidence_score', models.FloatField(help_text='Confidence (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('input_data', models.JSONField(blank=True, help_text='Input features used for prediction', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context and information', null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(help_text='Prediction subject', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'db_table': 'predictions',
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['animal', '-predicted_at'], name='animal_pred_idx'), models.Index(fields=['predicted_at'], name='pred_time_idx'), models.Index(fields=['prediction_type', 'predicted_at'], name='pred_type_time_idx')],
            },
        ),
    ]
