# Generated by Django 6.0.1 on 2026-02-09 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('health', 'Health Issue'), ('vaccination', 'Vaccination Due'), ('geofence', 'Geofence Breach'), ('battery', 'Low Battery'), ('weight', 'Weight Concern'), ('estrus', 'Estrus Cycle'), ('behavior', 'Abnormal Behavior'), ('temperature', 'Temperature Alert'), ('device', 'Device Issue'), ('prediction', 'AI Prediction')], help_text='Type of alert', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Alert severity level', max_length=20)),
                ('title', models.CharField(help_text='Short alert title', max_length=200)),
                ('message', models.TextField(help_text='Detailed alert description')),
                ('is_read', models.BooleanField(default=False, help_text='User has viewed this alert')),
                ('is_resolved', models.BooleanField(default=False, help_text='Alert issue has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When alert was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Alert generation timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('animal', models.ForeignKey(blank=True, help_text='Related animal (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='livestock.animal')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='alerts_aler_created_574618_idx'), models.Index(fields=['is_resolved', 'severity'], name='alerts_aler_is_reso_27cfbc_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='alerts_aler_alert_t_b65164_idx'), models.Index(fields=['animal', '-created_at'], name='alerts_aler_animal__c1d1b3_idx')],
            },
        ),
    ]
