# Generated by Django 4.2.9 on 2026-02-02 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Unique tag/ID for the animal', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for the animal', max_length=100)),
                ('breed', models.CharField(choices=[('BORAN', 'Boran'), ('ANKOLE', 'Ankole'), ('FRIESIAN', 'Friesian'), ('JERSEY', 'Jersey'), ('CROSS', 'Cross Breed'), ('OTHER', 'Other')], default='BORAN', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(help_text='Date of birth')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased'), ('QUARANTINE', 'Quarantine')], default='ACTIVE', max_length=20)),
                ('ranch_id', models.CharField(default='KISOMBWA_MAIN', help_text='Ranch location identifier', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Color/markings description', max_length=100)),
                ('weight_at_birth', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kg', max_digits=6, null=True)),
                ('collar_id', models.CharField(blank=True, help_text='Associated IoT collar device ID', max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('qr_code', models.ImageField(blank=True, help_text='Auto-generated QR code', upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, help_text='Mother', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_dam', to='livestock.animal')),
                ('sire', models.ForeignKey(blank=True, help_text='Father', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_sire', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('measured_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any observations during weighing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Weight Record',
                'verbose_name_plural': 'Weight Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(help_text='Name of the vaccine', max_length=200)),
                ('disease', models.CharField(blank=True, help_text='Disease prevented', max_length=200)),
                ('date_administered', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(help_text='When the next dose is due')),
                ('batch_number', models.CharField(blank=True, help_text='Vaccine batch number', max_length=100)),
                ('administered_by', models.CharField(blank=True, help_text='Veterinarian or staff name', max_length=100)),
                ('dosage', models.CharField(blank=True, help_text='Dosage administered', max_length=50)),
                ('route', models.CharField(blank=True, help_text='Route of administration (e.g., IM, SC)', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-date_administered'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(help_text='What was diagnosed', max_length=200)),
                ('symptoms', models.TextField(blank=True, help_text='Observed symptoms')),
                ('treatment', models.TextField(help_text='Treatment administered')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('follow_up_date', models.DateField(blank=True, help_text='When to check again', null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, help_text='Veterinarian or staff name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-date'],
            },
        ),
    ]
