# Generated by Django 6.0.1 on 2026-02-10 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(db_index=True, help_text='Unique key for the setting', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display label for the setting', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the setting')),
                ('category', models.CharField(choices=[('alerts', 'Alert Settings'), ('notifications', 'Notification Settings'), ('thresholds', 'Threshold Settings'), ('general', 'General Settings')], default='general', max_length=50)),
                ('setting_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('string', 'String')], default='boolean', max_length=20)),
                ('boolean_value', models.BooleanField(default=False)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('string_value', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this setting is currently enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['category', 'label'],
            },
        ),
    ]
