# Generated by Django 6.0.1 on 2026-02-09 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('device_id', models.CharField(max_length=50, unique=True, db_index=True)),
                ('firmware_version', models.CharField(max_length=20, default='1.0.0')),
                ('battery_level', models.IntegerField(default=100)),
                ('status', models.CharField(max_length=20, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active')),
                ('last_seen', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_device', to='core.animal')),
                ('ranch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.ranch')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(null=True, blank=True)),
                ('satellites', models.IntegerField(default=0)),
                ('body_temperature', models.FloatField()),
                ('ambient_temperature', models.FloatField()),
                ('acc_x', models.FloatField()),
                ('acc_y', models.FloatField()),
                ('acc_z', models.FloatField()),
                ('activity_level', models.FloatField(null=True, blank=True)),
                ('battery_level', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='core.animal')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='iot.device')),
            ],
            options={
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device', '-timestamp'], name='sensor_data_device_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['animal', '-timestamp'], name='sensor_data_animal_ts_idx'),
        ),
    ]
